---
- name: provision infrastructure
  hosts: "{{ lookup('pipe', 'hostnamectl hostname') }}, server"

  pre_tasks:
    - name: set the combined vars dict elements as facts
      loop: "{{ combined_vars | dict2items }}"
      set_fact:
        "{{ item.key }}": "{{ item.value }}"
      tags: always

    - name: update the package manager cache
      become: true
      package:
        update_cache: true
      changed_when: false
      tags:
        - network
        - packages

  roles:
    - role: network
      tags: network

    - role: packages
      tags: packages

    - role: file-sync
      tags: file-sync

    - role: git-repos
      tags: git-repos

    - role: config
      tags: config

    - role: services
      tags: services

  post_tasks:
    - name: print the package summary
      when: package_summary is defined and package_summary != ''
      debug:
        var: package_summary
      tags: packages
