---
- name: Provision infrastructure
  hosts: "{{ lookup('pipe', 'hostnamectl hostname') }}, server"

  pre_tasks:
    - name: Set the combined vars dict elements as facts
      loop: "{{ combined_vars | dict2items }}"
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ item.value }}"
      tags: always

    - name: Update the package manager cache
      become: true
      ansible.builtin.package:
        update_cache: true
      changed_when: false
      tags:
        - network
        - packages

  roles:
    - role: network
      tags: network

    - role: packages
      tags: packages

    - role: file-sync
      tags: file-sync

    - role: git-repos
      tags: git-repos

    - role: config
      tags: config

    - role: services
      tags: services

  post_tasks:
    - name: Print the package summary
      when: packages_summary is defined and packages_summary != ''
      ansible.builtin.debug:
        var: packages_summary
      tags: packages
