---
- name: append {{ process }} to package summary
  set_fact:
    package_summary: |
      {{ package_summary | default('') }}
      - {{ process }}:
          {{ task_result.stdout | default('') | indent }}
  when: task_result.changed
