---
- name: Append to package summary - {{ process }} # noqa: no-handler
  ansible.builtin.set_fact:
    packages_summary: |
      {{ packages_summary | default('') }}
      - {{ process }}:
          {{ task_result.stdout | default('') | indent }}
  when: task_result.changed
