---
- name: Set up tailscale
  when: server
  ansible.builtin.import_tasks: tailscale.yml

- name: Install and update system packages
  ansible.builtin.import_tasks: system.yml

- name: Install and update flatpak packages
  when: desktop
  ansible.builtin.import_tasks: flatpak.yml

- name: Install and update AUR packages
  when: desktop
  ansible.builtin.import_tasks: aur.yml
