---
- name: Allow ssh connections in the home server firewall
  when: server
  become: true
  community.general.ufw:
    rule: allow
    name: ssh

- name: Enable ufw
  become: true
  community.general.ufw:
    state: enabled
    default: deny

- name: Enable and start the ufw service
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: ufw
