---
- name: (desktop) check internet access
  when: desktop
  command: ping -c 1 1.1.1.1
  register: ping
  changed_when: false
  ignore_errors: true

- name: (desktop) set up the wifi connection
  when:
    - desktop
    - ping.failed
  include_tasks: wifi.yml

- name: ensure required network packages are installed
  become: true
  package:
    state: present
    name: "{{ package_list.system.network }}"

- name: check if firewall is enabled
  become: true
  command: ufw status
  register: firewall
  changed_when: false

- name: set up the firewall
  when: "'Status: inactive' in firewall.stdout"
  include_tasks: firewall.yml

- name: (desktop) create the user ssh key
  when: desktop
  user:
    name: "{{ ansible_facts.env.USER }}"
    generate_ssh_key: true
    ssh_key_type: ed25519

- name: (desktop) create the home server host entry
  when:
    - desktop
    - "'ip' in home_server"
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: ^.*\s{{ home_server.hostname }}$
    line: "{{ home_server.ip }} {{ home_server.hostname }}"

- name: (server) add the pc user public ssh key to authorized keys
  when: server
  authorized_key:
    user: "{{ ansible_facts.env.USER }}"
    key: "{{ lookup('file', lookup ('env', 'HOME') ~ '/.ssh/id_ed25519.pub') }}"

- name: automatically accept new host keys in ssh connections
  lineinfile:
    create: true
    path: "{{ ansible_facts.env.HOME }}/.ssh/config"
    regexp: ^StrictHostKeyChecking
    line: StrictHostKeyChecking=accept-new
