---
- name: Set up various config files
  loop:
    - {src: gitconfig.j2, dest: .gitconfig}
    - {src: ssh-config.j2, dest: .ssh/config}
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ ansible_facts.env.HOME }}/{{ item.dest }}"
    mode: '0644'

- name: Configure user-specific settings
  loop:
    - {user: root, home: /root, become: true}
    - {
      user: "{{ ansible_facts.env.USER }}",
      home: "{{ ansible_facts.env.HOME }}",
      become: false
    }
  ansible.builtin.include_tasks:
    file: user-specific.yml
    apply:
      become: "{{ item.become }}"

- name: Symlink the neovim binary to vim
  become: true
  ansible.builtin.file:
    state: link
    src: /usr/bin/nvim
    dest: /usr/bin/vim

- name: Set up vdirsyncer
  when: desktop
  ansible.builtin.import_tasks: vdirsyncer.yml

- name: Add user to the docker group
  when: desktop
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts.env.USER }}"
    groups: docker
    append: true

- name: Enable sddm autologin
  when: desktop
  become: true
  ansible.builtin.blockinfile:
    create: true
    path: /etc/sddm.conf.d/kde_settings.conf
    mode: '0644'
    block: |
      [Autologin]
      Relogin=false
      Session=plasmax11
      User={{ ansible_facts.env.USER }}
