---
- name: Create ~/.config directory for {{ item.user }}
  become: "{{ item.become }}"
  ansible.builtin.file:
    state: directory
    path: "{{ item.home }}/.config"
    mode: '0755'

- name: Set zsh as the default shell for {{ item.user }}
  ansible.builtin.user:
    name: "{{ item.user }}"
    shell: /usr/bin/zsh

- name: Symlink zsh config to ~/.config for {{ item.user }}
  ansible.builtin.file:
    state: link
    src: "{{ ansible_facts.env.HOME }}/git/zsh"
    dest: "{{ item.home }}/.config/zsh"

- name: Symlink .zshenv to home for {{ item.user }}
  ansible.builtin.file:
    state: link
    src: "{{ item.home }}/.config/zsh/.zshenv"
    dest: "{{ item.home }}/.zshenv"

- name: Symlink nvim config to ~/.config for {{ item.user }}
  when: desktop
  ansible.builtin.file:
    state: link
    src: "{{ ansible_facts.env.HOME }}/git/nvim"
    dest: "{{ item.home }}/.config/nvim"
