---
- name: create ~/.config directory for {{ item.user }}
  become: "{{ item.become }}"
  file:
    state: directory
    path: "{{ item.home }}/.config"

- name: set zsh as the default shell for {{ item.user }}
  user:
    name: "{{ item.user }}"
    shell: /usr/bin/zsh

- name: symlink zsh config to ~/.config for {{ item.user }}
  file:
    state: link
    src: "{{ ansible_facts.env.HOME }}/git/zsh"
    dest: "{{ item.home }}/.config/zsh"

- name: symlink .zshenv to home for {{ item.user }}
  file:
    state: link
    src: "{{ item.home }}/.config/zsh/.zshenv"
    dest: "{{ item.home }}/.zshenv"

- name: symlink nvim config to ~/.config for {{ item.user }}
  when: desktop
  file:
    state: link
    src: "{{ ansible_facts.env.HOME }}/git/nvim"
    dest: "{{ item.home }}/.config/nvim"
