---
- name: (desktop) check access to github
  when: desktop
  command: ssh -T git@github.com
  register: github_access
  changed_when: false
  failed_when: github_access.rc != 1
  ignore_errors: true

- name: clone all repositories
  loop: "{{ git_repositories }}"
  git:
    repo: "{{ git.remotes.home_server }}/{{ item }}"
    dest: "{{ ansible_facts.env.HOME }}/git/{{ item }}"
    update: false

- name: configure remotes for all repositories
  loop: "{{ git_repositories }}"
  environment:
    GITHUB_ACCESS: "{{
      github_access is success
      and github_access is not skipped
      | lower
    }}"
    GITHUB_URL: "{{ git.remotes.github }}/{{ item }}"
    SERVER_URL: "{{ git.remotes.home_server }}/{{ item }}"
  script:
    chdir: "{{ ansible_facts.env.HOME }}/git/{{ item }}"
    cmd: git_remote_setup.sh
  register: remote_setup
  changed_when: "'remotes unchanged' not in remote_setup.stdout"

- name: (desktop) pull repositories
  loop: "{{ git_repositories }}"
  when:
    - desktop
    - item != "ansible"
  shell:
    chdir: "{{ ansible_facts.env.HOME }}/git/{{ item }}"
    cmd: git pull --rebase origin $(git branch --show-current)
  register: pull
  changed_when: "'changed' in pull.stdout"

- name: (desktop) push to all remotes
  loop: "{{ git_repositories }}"
  when: desktop
  shell:
    chdir: "{{ ansible_facts.env.HOME }}/git/{{ item }}"
    cmd: |
      set -e
      for remote in $(git remote); do
        git push "$remote" $(git branch --show-current)
      done
  register: push
  changed_when: >
    push.stderr_lines
    | reject('match', 'Everything up-to-date')
    | length > 0

- name: (server) pull repositories
  when: server
  loop: "{{ git_repositories }}"
  shell:
    chdir: "{{ ansible_facts.env.HOME }}/git/{{ item }}"
    cmd: git pull --rebase origin $(git branch --show-current)
  register: pull
  changed_when: "'changed' in pull.stdout"
