---
- name: Check if the backup marker exists
  when: server
  ansible.builtin.stat:
    path: "{{ ansible_facts.env.HOME }}/.rcloned"
  register: backup_marker

- name: Fail if the backup marker is missing
  when:
    - server
    - not backup_marker.stat.exists
  ansible.builtin.fail:
    msg: "backup marker missing, please use rclone to restore home server files"

- name: Create a cronjob for file backup
  when: server
  ansible.builtin.cron:
    name: 'file backup'
    minute: 0
    hour: 4
    job: '$HOME/automation/backup.sh'

- name: Check if syncthing directories are already being synced
  when: desktop
  loop: "{{ syncthing_directories }}"
  ansible.builtin.stat:
    path: "{{ ansible_facts.env.HOME }}/{{ item.dest }}/.stfolder"
  register: stfolders

- name: Set up syncthing directories
  when: desktop
  loop: "{{ stfolders.results | rejectattr('stat.exists') | map(attribute='item') }}"
  ansible.builtin.include_tasks: syncthing_dir.yml
