---
- name: (server) check if the backup marker exists
  when: server
  stat:
    path: "{{ ansible_facts.env.HOME }}/.rcloned"
  register: backup_marker

- name: (server) fail if the backup marker is missing
  when:
    - server
    - not backup_marker.stat.exists
  fail:
    msg: "backup marker missing, please use rclone to restore home server files"

- name: (desktop) set up syncthing directories
  when: desktop
  loop: "{{ syncthing_directories }}"
  include_tasks: syncthing_dir.yml
