---
- name: check if the backup marker exists
  when: server
  stat:
    path: "{{ ansible_facts.env.HOME }}/.rcloned"
  register: backup_marker

- name: fail if the backup marker is missing
  when:
    - server
    - not backup_marker.stat.exists
  fail:
    msg: "backup marker missing, please use rclone to restore home server files"

- name: create a cronjob for file backup
  when: server
  cron:
    name: 'file backup'
    minute: 0
    hour: 4
    job: '$HOME/automation/backup.sh'

- name: set up syncthing directories
  when: desktop
  loop: "{{ syncthing_directories }}"
  include_tasks: syncthing_dir.yml
