---
- name: Copy syncthing directory (~/{{ item.dest }})
  ansible.posix.synchronize:
    src: "{{ home_server.hostname }}:syncthing/{{ item.src }}/"
    dest: "{{ ansible_facts.env.HOME }}/{{ item.dest }}/"

- name: Check if stignore.txt exists (~/{{ item.dest }})
  ansible.builtin.stat:
    path: "{{ ansible_facts.env.HOME }}/{{ item.dest }}/stignore.txt"
  register: stignore

- name: Include stignore.txt in .stignore (~/{{ item.dest }})
  when:
    - stignore.stat.exists
    - stignore.stat.isreg
  ansible.builtin.lineinfile:
    create: true
    path: "{{ ansible_facts.env.HOME }}/{{ item.dest }}/.stignore"
    mode: '0644'
    line: '#include stignore.txt'
