---
- name: Allow kdeconnect traffic in ufw
  when: desktop
  become: true
  loop:
    - tcp
    - udp
  community.general.ufw:
    rule: allow
    port: 1714:1764
    proto: "{{ item }}"
    comment: "kde connect"

- name: Allow syncthing traffic in ufw
  become: true
  community.general.ufw:
    rule: allow
    name: syncthing

- name: Allow syncthing GUI traffic in ufw
  when: server
  become: true
  community.general.ufw:
    rule: allow
    name: syncthing-gui

- name: Reload ufw to apply changes
  become: true
  community.general.ufw:
    state: reloaded
  changed_when: false

- name: Enable systemd system services
  when: services.system is defined
  become: true
  loop: "{{ services.system }}"
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ item }}"

- name: Enable systemd user services
  when: services.user is defined
  loop: "{{ services.user }}"
  ansible.builtin.systemd:
    scope: user
    state: started
    enabled: true
    name: "{{ item }}"
