---
- name: Allow kdeconnect traffic in ufw
  when: desktop
  become: true
  loop:
    - tcp
    - udp
  community.general.ufw:
    rule: allow
    port: 1714:1764
    proto: "{{ item }}"
    comment: "kde connect"

- name: Allow syncthing traffic in ufw
  become: true
  community.general.ufw:
    rule: allow
    name: syncthing

- name: Allow syncthing GUI traffic in ufw
  when: server
  become: true
  community.general.ufw:
    rule: allow
    name: syncthing-gui

- name: Reload ufw to apply changes
  become: true
  community.general.ufw:
    state: reloaded
  changed_when: false

- name: Sync vdirsyncer with the dav server
  when: desktop
  ansible.builtin.shell: |
    vdirsyncer discover
    vdirsyncer sync
  register: services_vdirsyncer_sync
  changed_when: "'uploading' in services_vdirsyncer_sync.stderr"

- name: Configure the vdirsyncer timer service
  when: desktop
  become: true
  loop:
    - {var: "OnBootSec", value: '1m'}
    - {var: "OnUnitActiveSec", value: '5m'}
    - {var: "AccuracySec", value: '1m'}
  ansible.builtin.lineinfile:
    path: "/usr/lib/systemd/user/vdirsyncer.timer"
    regexp: "{{ item.var }}="
    line: "{{ item.var }}={{ item.value }}"
  register: services_vdirsyncer_timer_config

- name: Enable systemd system services
  when: services.system is defined
  become: true
  loop: "{{ services.system }}"
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ item }}"

- name: Enable systemd user services
  when: services.user is defined
  loop: "{{ services.user }}"
  vars:
    restart_conditions:
      - "{{ item == 'vdirsyncer.timer' }}"
      - "{{ services_vdirsyncer_timer_config.changed }}"
  ansible.builtin.systemd:
    scope: user
    state: "{{ 'restarted' if restart_conditions is all else 'started' }}"
    enabled: true
    name: "{{ item }}"
