---
- name: Configure ufw rules
  become: true
  loop: "{{ ufw_rules }}"
  community.general.ufw:
    rule: "{{ item.rule }}"
    name: "{{ item.name | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
  register: services_ufw_config

- name: Reload ufw to apply changes # noqa: no-handler
  when: services_ufw_config.changed
  become: true
  community.general.ufw:
    state: reloaded

- name: Enable systemd system services
  when: services.system is defined
  become: true
  loop: "{{ services.system }}"
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ item }}"

- name: Enable systemd user services
  when: services.user is defined
  loop: "{{ services.user }}"
  ansible.builtin.systemd:
    scope: user
    state: started
    enabled: true
    name: "{{ item }}"
